name: Main

on: push

jobs:
  main:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1' ]

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpunit
        run: composer run-script phpunit -- --coverage-clover=coverage.xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./coverage.xml
          flags: tests

      - name: Run phpstan
        run: composer run-script phpstan

      - name: Run phpcs
        run: composer run-script phpcs

      - name: Run phpmd
        run: composer run-script phpmd

      - name: Security check
        run: composer update --dry-run roave/security-advisories

      - name: License check
        run: composer run-script check-license
